name: elec
description: A collection of elec functionality
version: 2.1.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  csv: ^6.0.0
  date:
    git: https://github.com/thumbert/date.git
  dama:
    git: https://github.com/thumbert/dama.git
  decimal: ^3.0.0
  dotenv: ^3.0.0
  duckdb_dart: ^0.4.0
  elec_server:
      git: https://github.com/thumbert/elec-server.git
  http: ^1.2.0
  intl: ^0.19.0
  mongo_dart: ^0.10.3
  more: ^4.6.1
  quiver: ^3.2.1
  statemachine: ^3.3.1
  table:
    git: https://github.com/thumbert/table.git
  timeseries:
    git: https://github.com/thumbert/timeseries.git
  timezone: ^0.9.4
  xml: ^6.3.0

dependency_overrides:
  decimal: ^3.0.0


dev_dependencies:
  lints: ^6.0.0
  test: ^1.17.4
